# Generated by Django 3.1 on 2020-09-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_box_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='recipe_box_app.Recipe'),
        ),
    ]
